# Generated by Django 4.2.4 on 2023-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
